"""Shared API for m2_dual_track_v1. Coordinator-owned. Versioned.

Workers implement against these types. Do not edit this file from a worker
prompt. If a change is required, stop and ask the coordinator to bump
CONTRACT_VERSION and notify both other workers.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Mapping, Protocol, Sequence

import numpy as np
import torch

from . import plan

CONTRACT_VERSION = plan.CONTRACT_VERSION


@dataclass(frozen=True)
class SessionBank:
    """Immutable per-session frozen calibration memory.

    Shapes (FP32 unless noted):
      frozen_u: [K, N, 64] or None
      E0:       [N, 50]
      T:        [N, 4]
      unit_mask:[N] bool
      X_store / target_store are compact query arrays used by the shared
      pipeline; candidates must not mutate them.
    """

    session_id: str
    support_trial_ids: tuple[int, ...]
    raw_trial_ids: tuple[int, ...]
    X_store: np.ndarray
    target_store: np.ndarray
    eligible_starts: np.ndarray
    E0: torch.Tensor
    T: torch.Tensor
    unit_mask: torch.Tensor
    provenance: dict[str, Any]
    frozen_u: torch.Tensor | None = None

    def __post_init__(self) -> None:
        plan.require(self.session_id, "session_id required")
        plan.require(self.E0.ndim == 2 and self.E0.shape[-1] == plan.IDENTITY_DIM, "E0 shape")
        plan.require(self.T.ndim == 2 and self.T.shape[-1] == plan.T4_DIM, "T shape")
        plan.require(self.E0.shape[0] == self.T.shape[0], "E0/T unit mismatch")
        if self.frozen_u is not None:
            plan.require(self.frozen_u.ndim == 3, "frozen_u must be [K,N,64]")
            plan.require(self.frozen_u.shape[1] == self.E0.shape[0], "frozen_u units")
            plan.require(self.frozen_u.shape[2] == plan.HIDDEN_DIM, "frozen_u hidden")


@dataclass
class Batch:
    session_id: str
    X: torch.Tensor
    last_target: torch.Tensor
    bank: SessionBank
    window_ids: tuple[int, ...]
    unit_mask: torch.Tensor | None = None

    def __post_init__(self) -> None:
        plan.require(self.X.ndim == 3, "X must be [B,W,N]")
        plan.require(self.X.shape[1] == plan.WINDOW, "window size")
        plan.require(self.last_target.ndim == 2 and self.last_target.shape[1] == plan.OUT_DIM, "target")
        plan.require(self.X.shape[0] == self.last_target.shape[0], "batch mismatch")
        plan.require(len(self.window_ids) == self.X.shape[0], "window_ids length")


@dataclass(frozen=True)
class SessionMetrics:
    session_id: str
    r2: float
    window_count: int
    prediction_digest: str
    extras: dict[str, Any] = field(default_factory=dict)


class Candidate(Protocol):
    name: str
    training_target_space: str

    def forward_last(
        self,
        X: torch.Tensor,
        bank: SessionBank,
        unit_mask: torch.Tensor | None = None,
    ) -> torch.Tensor:
        """Return [B, 2] in TRAINING_TARGET_SPACE (decoder_raw)."""

    def trainable_parameters(self) -> dict[str, torch.nn.Parameter]:
        """Explicit allowlist of name -> parameter. Frozen params omitted."""

    def train(self, mode: bool = True) -> Any:
        ...

    def eval(self) -> Any:
        ...


class Evaluator(Protocol):
    def __call__(
        self,
        candidate: Candidate,
        scoring_manifest: Mapping[str, Any],
    ) -> dict[str, Any]:
        """Per-session metrics + prediction digest. Development evidence."""


def make_stub_bank(
    *,
    session_id: str = "stub",
    num_units: int = plan.CHANNELS,
    k: int = plan.SUPPORT_HORIZON,
    seed: int = 0,
    device: torch.device | None = None,
) -> SessionBank:
    """Synthetic bank for worker-local tests. Not a scoring authority."""
    rng = np.random.default_rng(seed)
    device = device or torch.device("cpu")
    e0 = torch.from_numpy(rng.standard_normal((num_units, plan.IDENTITY_DIM)).astype(np.float32)).to(device)
    t = torch.from_numpy(rng.standard_normal((num_units, plan.T4_DIM)).astype(np.float32)).to(device)
    u = torch.from_numpy(rng.standard_normal((k, num_units, plan.HIDDEN_DIM)).astype(np.float32)).to(device)
    mask = torch.ones(num_units, dtype=torch.bool, device=device)
    x_store = rng.standard_normal((8, plan.WINDOW, num_units)).astype(np.float32)
    target = rng.standard_normal((8, plan.OUT_DIM)).astype(np.float32)
    starts = np.arange(8, dtype=np.int64)
    return SessionBank(
        session_id=session_id,
        support_trial_ids=tuple(range(k)),
        raw_trial_ids=tuple(range(k)),
        X_store=x_store,
        target_store=target,
        eligible_starts=starts,
        E0=e0,
        T=t,
        unit_mask=mask,
        provenance={"kind": "synthetic_stub", "contract_version": CONTRACT_VERSION},
        frozen_u=u,
    )


def make_stub_batch(bank: SessionBank, batch_size: int = 4, seed: int = 1) -> Batch:
    rng = np.random.default_rng(seed)
    n = int(bank.E0.shape[0])
    x = torch.from_numpy(rng.standard_normal((batch_size, plan.WINDOW, n)).astype(np.float32)).to(bank.E0.device)
    y = torch.from_numpy(rng.standard_normal((batch_size, plan.OUT_DIM)).astype(np.float32)).to(bank.E0.device)
    return Batch(
        session_id=bank.session_id,
        X=x,
        last_target=y,
        bank=bank,
        window_ids=tuple(range(batch_size)),
        unit_mask=bank.unit_mask,
    )


def assert_contract_version(expected: int = CONTRACT_VERSION) -> None:
    if expected != CONTRACT_VERSION:
        raise plan.DualTrackError(
            f"contract version mismatch: worker={expected} coordinator={CONTRACT_VERSION}"
        )


def variance_weighted_r2(target: np.ndarray, prediction: np.ndarray) -> float:
    y = np.asarray(target, dtype=np.float64)
    p = np.asarray(prediction, dtype=np.float64)
    plan.require(y.ndim == 2 and y.shape[1] == 2 and p.shape == y.shape, "R2 shape")
    plan.require(y.shape[0] >= 2, "R2 needs >=2 rows")
    plan.require(bool(np.isfinite(y).all() and np.isfinite(p).all()), "R2 nonfinite")
    residual = np.square(y - p).sum(axis=0, dtype=np.float64)
    centered = y - y.mean(axis=0, keepdims=True)
    total = np.square(centered).sum(axis=0, dtype=np.float64)
    denom = float(total.sum(dtype=np.float64))
    plan.require(denom > 0.0, "R2 target variance is zero")
    return float(1.0 - residual.sum(dtype=np.float64) / denom)


def summarize_sessions(values: Mapping[str, float]) -> dict[str, object]:
    plan.require(bool(values), "empty session map")
    ordered = {key: float(values[key]) for key in sorted(values)}
    array = np.asarray(list(ordered.values()), dtype=np.float64)
    plan.require(bool(np.isfinite(array).all()), "session R2 nonfinite")
    return {
        "session_count": int(array.size),
        "equal_session_mean": float(array.mean()),
        "equal_session_median": float(np.median(array)),
        "per_session_r2": ordered,
    }


def date_equal_mean(per_session: Mapping[str, float]) -> dict[str, object]:
    by_date: dict[str, list[float]] = {}
    for session, value in per_session.items():
        date = session.replace("ses-", "").rsplit("-Run", 1)[0]
        by_date.setdefault(date, []).append(float(value))
    date_means = {date: float(np.mean(vals)) for date, vals in sorted(by_date.items())}
    return {
        "per_date_mean": date_means,
        "equal_date_mean": float(np.mean(list(date_means.values()))) if date_means else float("nan"),
    }
