from __future__ import annotations
import numpy as np
from types import SimpleNamespace
from sua_exploration.mc_maze import h1_event_carrier_nle5 as nle5
from sua_exploration.mc_maze import h1_sparse_event_endpoint as v1


def _z(n=24):
    rng=np.random.default_rng(44); z=rng.normal(size=(n,4)); assert np.linalg.matrix_rank(np.c_[np.ones(n),z])==5; return z


def test_nle5_fixed_small_model_and_width() -> None:
    assert (nle5.RANK,nle5.CARRIER_DIM,nle5.RFF_WIDTH,nle5.RFF_SEED)==(4,5,16,190271)
    assert nle5.SUPPORT_BUDGETS==(3,4)


def test_nle5_synthetic_nonlinear_latent_closed_form_recovery() -> None:
    z=_z(); slopes=np.zeros((4,v1.EXPECTED_NEURONS)); slopes[:,:4]=np.array([[.6,-.4,.1,.2],[.2,.3,-.2,.1],[.1,0,.3,-.2],[-.2,.2,.1,.4]])
    y=z@slopes+np.linspace(-.3,.3,v1.EXPECTED_NEURONS)
    carrier,meta=nle5.fit_carrier(z,y)
    x=np.c_[np.ones(len(z)),z]; penalty=np.diag([0.]+[1.]*4)*(len(z)*nle5.TARGET_RIDGE_LAMBDA)
    expected=np.linalg.solve(x.T@x+penalty,x.T@y)
    np.testing.assert_allclose(carrier,np.c_[expected[1:].T,expected[0]],atol=1e-12,rtol=0)
    assert carrier.shape==(176,5) and meta["target_optimizer_steps"]==meta["target_backward_steps"]==0


def test_nle5_label_and_row_shuffle_destroy_attachment() -> None:
    z=_z(); y=np.zeros((len(z),176)); y[:,0]=z[:,0]+.4*z[:,1]
    correct,_=nle5.fit_carrier(z,y); order,manifest=nle5._fixed_permutation(len(z),"synthetic-label")
    wrong,_=nle5.fit_carrier(z[order],y); rows,rowmanifest=nle5._fixed_permutation(176,"synthetic-row")
    assert manifest["fixed_points"]==rowmanifest["fixed_points"]==0
    assert not np.array_equal(correct,wrong) and not np.array_equal(correct,correct[rows])


def test_nle5_coordinate_rotation_is_prediction_invariant_and_deterministic() -> None:
    z=_z(); y=np.zeros((len(z),176)); y[:,:3]=z@np.array([[.2,.1,-.1],[.1,-.2,.4],[.3,0,.2],[0,.1,.1]])
    rotation=nle5._rotation(); a,_=nle5.fit_carrier(z,y); b,_=nle5.fit_carrier(z@rotation,y)
    np.testing.assert_allclose(nle5.predict(a,z),nle5.predict(b,z@rotation),atol=1e-12,rtol=0)
    np.testing.assert_array_equal(rotation,nle5._rotation())


def test_nle5_outer_date_allowlist_excludes_outer() -> None:
    names=nle5.source_names_for_outer("19250101"); assert len(names)==11 and all(v1.session_date(x)!="19250101" for x in names)


def test_nle5_source_nonlinear_map_is_deterministic_and_tag_shuffle_changes_phi() -> None:
    events=[]
    for i in range(32):
        events.append(v1.MovementEvent(i,v1.MOVEMENT_TAGS[i % len(v1.MOVEMENT_TAGS)],float(i),i, float(i),float(i)+.2+.01*(i%3),.2+.01*(i%3),5,
            np.asarray([np.sin(i+j) for j in range(7)]),np.full(176,.01*i)))
    names=nle5.source_names_for_outer("19250101")
    sessions={name:SimpleNamespace(events=tuple(events)) for name in names}
    first=nle5.fit_nonlinear_map(sessions,outer_date="19250101"); second=nle5.fit_nonlinear_map(sessions,outer_date="19250101")
    np.testing.assert_array_equal(first.transform(events),second.transform(events))
    shuffled=[e.tag for e in events[::-1]]
    assert not np.array_equal(first.transform(events),first.transform(events,shuffled))
    # A target response generated by the nonlinear source phi is recovered by the same 5-D path.
    z=first.transform(events); response=np.zeros((len(z),176)); response[:,:2]=z@np.array([[.2,-.1],[.1,.3],[.4,.2],[-.2,.1]])
    carrier,_=nle5.fit_carrier(z,response)
    recovered=np.mean((nle5.predict(carrier,z)[:,:2]-response[:,:2])**2)
    intercept=np.mean((response[:,:2]-response[:,:2].mean(0))**2)
    assert recovered < intercept


def test_nle5_gate_requires_material_and_controls() -> None:
    good={"defined_sessions":13,"mean":.0201,"median":.0101,"positive":10,"leave_largest_absolute_out_mean":.0001}
    a={"correct_minus_hse5":good,"correct_minus_label_shuffle":good,"correct_minus_tag_shuffle":good,"correct_minus_row_shuffle":good,"correct_minus_intercept":good}
    assert nle5.gate(a)["passed"]
    assert not nle5.gate({**a,"correct_minus_tag_shuffle":{**good,"mean":-.01}})["passed"]
